# Generated by Django 5.2.17 on 2026-09-12 03:46

import django.db.models.deletion
import hooks.tokens
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Temporary endpoint', max_length=120)),
                ('ingest_token', models.CharField(default=hooks.tokens.generate_ingest_token, editable=False, max_length=64, unique=True)),
                ('management_token_hash', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('is_temporary', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebhookRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('headers', models.JSONField(default=dict)),
                ('query_params', models.JSONField(default=dict)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('body_raw', models.BinaryField(blank=True, default=bytes)),
                ('parsed_json', models.JSONField(blank=True, null=True)),
                ('body_size', models.PositiveBigIntegerField(default=0)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hooks.endpoint')),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['owner', '-created_at'], name='hooks_ep_owner_created'),
        ),
        migrations.AddConstraint(
            model_name='endpoint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_temporary', True), ('owner__isnull', True)), models.Q(('is_temporary', False), ('owner__isnull', False)), _connector='OR'), name='hooks_ep_owner_temp'),
        ),
        migrations.AddConstraint(
            model_name='endpoint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expires_at__isnull', False), ('is_temporary', True)), models.Q(('expires_at__isnull', True), ('is_temporary', False)), _connector='OR'), name='hooks_ep_expiry_temp'),
        ),
        migrations.AddIndex(
            model_name='webhookrequest',
            index=models.Index(fields=['endpoint', '-received_at'], name='hooks_req_ep_received'),
        ),
        migrations.AddIndex(
            model_name='webhookrequest',
            index=models.Index(fields=['endpoint', 'method'], name='hooks_req_ep_method'),
        ),
    ]
